# Generated by Django 4.2.2 on 2023-06-27 04:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_remove_email_id_email_date_created_email_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='uuid'),
        ),
    ]
