# Generated by Django 4.2.2 on 2023-10-06 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_email_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='phishing',
            field=models.BooleanField(default=False, verbose_name='phishing'),
            preserve_default=False,
        ),
    ]
