# Generated by Django 4.2.2 on 2023-10-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_email_phishing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='phishing',
            field=models.CharField(max_length=10, verbose_name='phishing'),
        ),
    ]
